config/routes.rb
Timetracker::Application.routes.draw do

  resources :tasks, :except => [:edit, :update] do
    resources :reports, :only => [:new, :create, :destroy]
    member do
      post 'finish'
    end
  end

  root :to => "tasks#index"

end

app/models/report.rb
class Report < ActiveRecord::Base
  validates_presence_of :task, :time
  validates_numericality_of :time, :only_integer => true

  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :name, :time
  validates_numericality_of :time, :only_integer => true

  has_many :reports, :dependent => :destroy

  def current_time
    self.reports.collect{|report| report.time}.sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
    load_task
    @report = @task.reports.new
  end

  def create
    load_task
    @report = @task.reports.new(params[:report])
    if @report.save
      redirect_to task_url(@task), :notice => "Report created!"
    else
      render :action => "new"
    end
  end

  def destroy
    load_task
    @task.reports.find(params[:id]).destroy
    redirect_to task_url(@task), :notice => "Report deleted!"
  end

  private

  def load_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to root_url, :notice => "Task created!"
    else
      render :action => "new"
    end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_url, :notice => "Task deleted!" 
  end

  def finish
    @task = Task.find(params[:id])
    @task.update_attribute("finished", true)
    redirect_to task_url(@task), :notice => "Task is finished!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!! 5
%head
  %meta{:charset => "utf-8"}
%body
  #flash
    #notice= flash[:notice]
    #error= flash[:error]
  #content
    = yield

app/views/reports/new.html.haml
%h2= "New report for #{@task.name}"
= simple_form_for [@task, @report] do |form|
  = form.input :time, :hint => "Write number of working hours you want to report"
  = form.submit "Create"

app/views/tasks/_task.html.haml
%h4= link_to task.name, task_url(task)
.task_details
  Time: 
  = task.time
  || Current time:
  = task.current_time
  || Finished: 
  = task.finished
.taks_options
  = button_to("delete", task_url(task), :method => :delete, :confirm => "Are you sure")
%hr

app/views/tasks/index.html.haml
%h2 Tasks
= link_to("New task", new_task_url)
= render :partial => @tasks

app/views/tasks/new.html.haml
%h2 New task
= simple_form_for @task do |f|
  = f.input :name
  = f.input :time, :hint => "Only number of minutes is acceptable. So type 120 if you worked 2 hours or 210 when it was 3,5 etc."
  = f.submit "Create"

app/views/tasks/show.html.haml
%h2= @task.name
.details
  Estimation:
  = @task.time
  %br
  Current time:
  = @task.current_time
  %br
  = link_to "Create report", new_task_report_url(@task) unless @task.finished
  %br
  = @task.finished ? "Finished" : button_to("finish task", finish_task_url(@task), :method => :post)
.reports
  - for report in @task.reports
    .report_details
      = "#{report.time} reported at #{report.created_at}"
      = button_to "Delete report", task_report_url(@task, report), :method => :delete, :confirm => "Are you sure?"